version: '3'

services:
    docker-registry:
        container_name: docker-registry
        image: registry:2
        ports:
            - 5000:5000
        restart: always
        environment:
           REGISTRY_AUTH: htpasswd
           REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
           REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
           REGISTRY_HTTP_TLS_CERTIFICATE: /certificates/domain.crt
           REGISTRY_HTTP_TLS_KEY: /certificates/domain.key
        volumes:
            - ./volume:/var/lib/registry
            - ./auth:/auth
            - /certificates:/certificates
    docker-registry-ui:
        container_name: docker-registry-ui
        image: konradkleine/docker-registry-frontend:v2
        ports:
            - 8080:80
        environment:
            ENV_DOCKER_REGISTRY_HOST: docker-registry
            ENV_DOCKER_REGISTRY_PORT: 5000
            ENV_DOCKER_REGISTRY_USE_SSL: 1
